# ============ init Section, Node ================
s1 = Section.create(id: 1, name: '区块资讯')
Node.create(id: 1, name: '头条', summary: '...', section_id: s1.id)
Node.create(id:2, name: '新闻资讯', summary: '...', section_id: s1.id)
s2 = Section.create(id:2, name: '区块技术')
Node.create(id: 3, name: '分布式系统', summary: '...', section_id: s2.id)
Node.create(id: 6, name: '区块链', summary: '...', section_id: s2.id)
Node.create(id: 4, name: '智能合约', summary: '...', section_id: s2.id)
Node.create(id: 5, name: '密码学', summary: '...', section_id: s2.id)
s3 = Section.create(id: 3, name: '区块应用')
Node.create(id: 6,name: '钱包', summary: '...', section_id: s3.id)
Node.create(id: 7,name: '比特币', summary: '...', section_id: s3.id)
Node.create(id: 8,name: '以太坊', summary: '...', section_id: s3.id)
Node.create(id: 9,name: '云养猫 / 区块链养宠', summary: '...', section_id: s3.id)
